version: "3.7"

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - SERVERURL=$DOMAIN #optional
      - SERVERPORT=$PORT #optional
      - PEERS=$PEERS #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=172.16.13.0 #optional
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
