version: "3.7"

services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: $NAME
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    environment:
      - TZ=Europe/Vienna
      - SERVERURL=$DOMAIN #optional
      - SERVERPORT=$PORT #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped


  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:0.3.7
    container_name: ${NAME}-ui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=alpha
      - WGUI_PASSWORD=this-unusual-password
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./config:/app/db
      - ./config:/etc/wireguard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$NAME.rule=Host(`$DOMAIN`) || Host(`www.$DOMAIN`)"
      - "traefik.http.middlewares.www-redirect-$NAME.redirectregex.regex=^https://$DOMAIN/(.*)"
      - "traefik.http.middlewares.www-redirect-$NAME.redirectregex.replacement=https://www.$DOMAIN/$${1}"
      - "traefik.http.middlewares.www-redirect-$NAME.redirectregex.permanent=true"
      - "traefik.http.routers.$NAME.middlewares=www-redirect-$NAME"
      - "traefik.http.routers.$NAME.entrypoints=https"
      - "traefik.http.routers.$NAME.tls=true"
      - "traefik.http.routers.$NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$NAME.loadbalancer.server.port=5000"
